/**/servo_bridge:
  ros__parameters:
    servo_controller:

      groups:
        - joints

      joints:
        angle_sgn: 1
        angle_scale: 0.00076699
        zero_point_offset: 2047
        torque_scale: 0.03483
        init_value: 1.57
        names:
          - joint1
          - joint2
          - joint3
        joint1:
            id: 0
            angle_sgn: -1
        joint2:
            id: 1
        joint3:
            id: 2            
        simulation:
          type: joint_group_position_controller

# joints setting for simulation
/**/joint_group_position_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
    interface_name: position
    gains:
        p: 100.0
        i: 0.0
        d: 10.0
    state_publish_rate: 100
